#!/usr/bin/env bash

git_path = '.git'
key = 'po'

for f in *; do
    if [ -d ${f} ]; then
        # Will not run if no directories are available
	cd $f/.git/
        if grep -Fxq "$key" config
	then
    		cd ../..
	else
		cp config ../
		rm config
		cd ../
    		cp ../config_alias .
		cat config_alias >> config
		mv config .git/
		sed -i.bak -e 's/^M$//' .git/config
		rm .git/config.bak
		rm config_alias
	fi
    fi
done

sed -i.bak -e 's/^M$//' config
cd ../

